create table Customer
(
    id        int primary key generated by default as identity,
    name      varchar(50)        not null,
    email     varchar(20)        not null unique,
    telephone varchar(11) unique not null
);

create table Orders
(
    id              int primary key generated by default as identity,
    delivery_address varchar(200) not null,
    total_cost       int check ( total_cost > 0 ),
    order_status     varchar(10),
    customer_id     int references Customer (id) on delete cascade
);

create table Products
(
    id          int primary key generated by default as identity,
    name        varchar(50) unique      not null,
    description varchar(50)             not null,
    price       int check ( price > 0 ) not null,
    count       int check ( count > 0 ),
    order_id    int                     references Orders (id) on delete set null
);

insert into Customer(name, email, telephone)
VALUES ('Margarita', 'margo18@gmail.com', '79276644401');
insert into Customer(name, email, telephone)
VALUES ('Miron', 'Mir@gmail.com', '79276644402');
insert into Customer(name, email, telephone)
VALUES ('Alena', 'Alencha@gmail.com', '79276644403');

insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('Moskow, Lenina 20', 1100, 'PROCESSING', 1);
insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('SPb, Black 18', 1500, 'ORDERED', 1);
insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('Chita, B.Yasnay 10', 10000, 'DELIVERED', 2);
insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('Moscow, Perovskoy 1', 80000, 'DELIVERED', 2);
insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('Moscow, Perovskoy 122', 49200, 'PROCESSING', 3);
insert into Orders(delivery_address, total_cost, order_status, customer_id)
VALUES ('Omsk, Strausov 12', 54000, 'DELIVERED', 3);


insert into Products(name, description, price, count, order_id)
VALUES ('cap', 'baseball cap', 550, 2, 1);
insert into Products(name, description, price, count, order_id)
VALUES ('small car', 'toy for kids game', 300, 5, 2);
insert into Products(name, description, price, count, order_id)
VALUES ('mirror', 'mirror for bath', 1000, 10, 3);
insert into Products(name, description, price, count, order_id)
VALUES ('laptop', 'new laptop for work', 80000, 1, 4);
insert into Products(name, description, price, count, order_id)
VALUES ('jacket', 'black with hood', 12300, 4, 5);
insert into Products(name, description, price, count, order_id)
VALUES ('boots', 'insulated, black', 27000, 2, 6);
